version: "3.8"
services:
  kafka-zookeeper:
    container_name: kafka-kraft
    build:
      context: .
      dockerfile: ./kraft.dockerfile
    image: sadavoya/learn-kafka
    ports:
      - "2181:2181"
    volumes:
      - /tmp/kraft-combined-logs
      - /tmp/zookeeper
      - /tmp/kafka-logs
    working_dir: /home
    stdin_open: true
    tty: true
